### ISSUE TITLE
Config file is not being generated

### ISSUE THREAD

**Issue by Gabb1995** [L41rx/ValheimFaveServers#2]
I started and exited valheim, even loaded a world and exited and config file is not being created.

**Comment by Fing3rz** [comment]
i was able to bypass this bug by just creating a config file with the proper name "net.l41rx.valheimfaveservers.cfg" and then launched the game to populate the file contents.

**Comment by L41rx** [comment]
verified bug and fixed in .0.1 (https://github.com/L41rx/ValheimFaveServers/releases/tag/1.0.1)
Sorry folks, didnt delete my config and test
